swagger: "2.0"
info:
  description: Stereopoly REST Api
  version: "1.0.0"
  title: Stereopoly REST Api
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /api

parameters:
  apiVersion:
    in: query
    name: api
    type: string
    description: API version used
    required: false
    default: "1.0.0"

responses:
  error:
    description: An error has occurred while handling the request. Check the error text for more details.
    schema:
      $ref: '#/definitions/error'

definitions:
  error:
    type: object
    description: Describes the error that occurred during the request.
    properties:
      error:
        type: string
        description: The error text.

paths:
  /boards:
    parameters:
      - $ref: '#/parameters/apiVersion'
    get:
      operationId: stereopoly.api.boards.get
      tags:
        - "Boards"
      summary: Board structure of the Stereopoly App
      description: Retrieve all boards currently in the database
      responses:
        200:
          description: Successful read board list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                version:
                  type: integer
                id:
                  type: integer
        400:
          $ref: '#/responses/error'