swagger: "2.0"
info:
  description: Stereopoly REST Api
  version: "1.0.0"
  title: Stereopoly REST Api
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: /api

parameters:
  apiVersion:
    in: query
    name: api
    type: string
    description: API version used
    required: false
    default: "1.0.0"

responses:
  error:
    description: An error has occurred while handling the request. Check the error text for more details.
    schema:
      $ref: '#/definitions/error'

definitions:
  error:
    type: object
    description: Describes the error that occurred during the request.
    properties:
      error:
        type: string
        description: The error text.
  money_scheme:
    type: object
    description: A money scheme used by boards
    properties:
      name:
        type: string
        description: The name (and formatting scheme) for the money scheme
      money:
        type: array
        items:
          type: integer
  news:
    type: object
    description: A news representation
    properties:
      text:
        type: string
        description: News text
      id:
        type: integer
        description: News ID
  newsgroup:
    type: object
    description: A certain group of news
    properties:
      news:
        type: array
        items:
          $ref: '#/definitions/news'
  board:
    type: object
    description: representation of a playable board in stereopoly
    properties:
      id:
        type: integer
        description: the board's id
      version:
        type: integer
        description: the board's current revision
      name:
        type: string
        description: Name of the board
      money_scheme:
        $ref: '#/definitions/money_scheme'
      newsgroups:
        type: array
        items:
          $ref: '#/definitions/newsgroup'

paths:
  /boards:
    parameters:
      - $ref: '#/parameters/apiVersion'
    get:
      operationId: stereopoly.api.boards.get_all
      tags:
        - "Boards"
      summary: Board structure of the Stereopoly App
      description: Retrieve all boards currently in the database
      responses:
        200:
          description: Successful read board list operation
          schema:
            type: array
            items:
              properties:
                name:
                  type: string
                version:
                  type: integer
                id:
                  type: integer
        400:
          $ref: '#/responses/error'
  /boards/{id}:
    parameters:
      - $ref: '#/parameters/apiVersion'
      - name: id
        in: path
        description: board id
        required: true
        type: integer
    get:
      operationId: stereopoly.api.boards.get
      tags:
        - "Boards"
      summary: Board structure of the Stereopoly App
      description: Retrieve a specific board currently in the database
      responses:
        200:
          description: Successful read board operation
          schema:
            $ref: '#/definitions/board'
        400:
          $ref: '#/responses/error'